# Generated by Django 2.1 on 2018-08-20 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0003_auto_20180820_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposed_law',
            name='final_time',
            field=models.TimeField(default=datetime.datetime(2018, 8, 20, 12, 19, 56, 40546), verbose_name='horario final'),
        ),
        migrations.AlterField(
            model_name='proposed_law',
            name='resultado',
            field=models.BooleanField(default=False, verbose_name='resultado'),
        ),
    ]
